[tool.poetry]
name = "01-intro-to-functions"
version = "0.1.0"
description = ""
authors = ["harryw1 <harrisonrweiss1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
